formapp/__init__.py
from flask import Flask

from .extensions import mongo
from .main.routes import main


def create_app():
    app = Flask(__name__)

    app.config['UPLOAD_FOLDER'] = "static/images"
    app.config['MONGO_URI'] = 'mongodb://localhost:27017/ewu_db'

    mongo.init_app(app)
    app.register_blueprint(main)

    return app

formapp/main/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from formapp.extensions import mongo
from werkzeug.utils import secure_filename

main = Blueprint('main', __name__)


@main.route('/')
def index():
    form_collection = mongo.db.form_db
    form = form_collection.find()
    return render_template('index.html', form=form)


@main.route('/form', methods=['POST'])
def form():
    form_collection = mongo.db.form_db
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    gender = request.form.get('gender')
    dateOfBirth = request.form.get('dateOfBirth')
    country = request.form.get('country')
    religion = request.form.get('religion')
    nationality = request.form.get('nationality')
    street1 = request.form.get('street1')
    street2 = request.form.get('street2')
    city = request.form.get('city')
    police_station = request.form.get('police_station')
    postal_code = request.form.get('postal_code')
    phone = request.form.get('phone')
    email = request.form.get('email')
    program = request.form.get('program')
    semester = request.form.get('semester')
    dpt_name = request.form.get('dpt_name')
    form_collection.insert_one({
        'first_name': first_name,
        'last_name': last_name,
        'gender': gender,
        'dateOfBirth': dateOfBirth,
        'country': country,
        'religion': religion,
        'nationality': nationality,
        'street1': street1,
        'street2': street2,
        'city': city,
        'police_station': police_station,
        'postal_code': postal_code,
        'phone': phone,
        'email': email,
        'program': program,
        'semester': semester,
        'dpt_name': dpt_name,
    })
    return redirect(url_for('main.index'))

@main.route('/all-forms')
def all_form():
    form_collection = mongo.db.form_db
    forms = form_collection.find({})
    return render_template('forms.html', forms=forms)

formapp/templates/forms.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>EWU Admission Form</title>
</head>

<body>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link text-dark" aria-current="page" href="{{ url_for('main.index') }}">Form</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.all_form') }}">All forms</a>
        </li>
    </ul>
    <div class="container my-3">
        <div class="row">
            {% for form in forms %}
            <div class="card card-body mb-2">
                Object ID: {{ form.get('_id') }}<br />
                First name: {{ form.get('first_name') }}<br />
                Last name: {{ form.get('last_name') }}<br />
                Email address: {{ form.get('email') }}<br />
                Gender: {{ form.get('gender') }}<br />
                Date of Birth: {{ form.get('dateOfBirth') }}<br />
                Country: {{ form.get('country') }}<br />
                Religion: {{ form.get('religion') }}<br />
                Nationality: {{ form.get('nationality') }}<br />
                Street 1: {{ form.get('street1') }}<br />
                {% if form.get('street2') %}
                Street 2: {{ form.get('street2') }}<br />
                {% endif %}
                City: {{ form.get('city') }}<br />
                Police station: {{ form.get('police_station') }}<br />
                Postal code: {{ form.get('postal_code') }}<br />
                Phone number: {{ form.get('phone') }}<br />
                Program name: {{ form.get('program') }}<br />
                Semester: {{ form.get('semester') }}<br />
                Department name: {{ form.get('dpt_name') }}
            </div>
            {% endfor %}
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

</html>

formapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>EWU Admission Form</title>
</head>

<body>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ url_for('main.index') }}">Form</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{{ url_for('main.all_form') }}">All forms</a>
        </li>
    </ul>
    <form action="{{ url_for('main.form') }}" method="POST" enctype="multipart/form-data">
        <div class="input-group">
            <div class="container my-3">
                <div class="col-md-8 con offset-md-2 formimage">
                    <div class="title bgimage">EWU Admission Form</div>
                    <div class="my-3">
                        <label class="form-label"><b>First Name</b></label>
                        <input type="text" class="form-control" id="first_name" name="first_name" required
                            placeholder="First name" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label"><b>Last Name</b></label>
                        <input type="text" class="form-control" name="last_name" placeholder="Last name" required />
                    </div>
                    <div class="row g-2 mb-3">
                        <div class="col">
                            <label class="form-label"><b>Gender</b></label>
                            <div class="form-check">
                                <div class="form-check form-check-inline me-5">
                                    <input class="form-check-input" type="radio" name="gender" value="male" />
                                    <label class="form-check-label">Male</label>
                                </div>
                                <div class="form-check form-check-inline me-5">
                                    <input class="form-check-input" type="radio" name="gender" value="female" />
                                    <label class="form-check-label">Female</label>
                                </div>
                                <div class="form-check form-check-inline me-5">
                                    <input class="form-check-input" type="radio" name="gender" value="other" />
                                    <label class="form-check-label">Others</label>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <label class="form-label"><b>Date Of Birth</b></label>
                            <input type="Date" class="form-control" name="dateOfBirth" required />
                        </div>
                    </div>
                    <div class="row g-2 mb-3">
                        <div class="col">
                            <label class="form-label"><b>Country</b></label>
                            <input type="text" class="form-control" name="country" placeholder="Country" required />
                        </div>
                        <div class="col">
                            <label class="form-label"><b>Religion</b></label>
                            <input type="text" class="form-control" name="religion" placeholder="Religion" required />
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label"><b>Nationality</b></label>
                        <input type="text" class="form-control" name="nationality" placeholder="Nationality" required />
                    </div>
                    <div class="mb-3">
                        <label class="form-label"><b>Address</b></label>
                        <input type="text" class="form-control mb-3" name="street1" placeholder="Street 1" required />
                        <input type="text" class="form-control" name="street2" placeholder="Street 2" />
                    </div>
                    <div class="row g-2 mb-3">
                        <div class="col">
                            <label class="form-label"><b>City</b></label>
                            <input type="text" class="form-control" name="city" placeholder="City" required />
                        </div>
                        <div class="col">
                            <label class="form-label"><b>Thana</b></label>
                            <input type="text" class="form-control" name="police_station" placeholder="Thana"
                                required />
                        </div>
                    </div>
                    <div class="mb-3 col-6">
                        <label class="form-label"><b>Postal Code</b></label>
                        <input type="text" class="form-control" name="postal_code" placeholder="Postal code" required />
                    </div>
                    <div class="row g-2 mb-3">
                        <div class="col">
                            <label class="form-label"><b>Phone Number</b></label>
                            <input type="text" class="form-control" name="phone" placeholder="Phone" required />
                        </div>
                        <div class="col">
                            <label class="form-label"><b>Email</b></label>
                            <input type="text" class="form-control" name="email" placeholder="Email" required />
                        </div>
                    </div>
                    <div class="row g-2 mb-3">
                        <div class="col">
                            <label class="form-label"><b>Select Program</b></label>
                            <select class="form-select" name="program" required>
                                <option selected value="0" disabled>Select Program</option>
                                <option value="1">Undergraduate</option>
                                <option value="2">Masters</option>
                                <option value="3">PhD</option>
                            </select>
                        </div>
                        <div class="col p-2">
                            <label class="form-label"><b>Select Semester</b></label>
                            <div class="form-check">
                                <div class="form-check form-check-inline me-5">
                                    <input class="form-check-input" type="radio" name="semester" value="spring" />
                                    <label class="form-check-label">Spring</label>
                                </div>
                                <div class="form-check form-check-inline me-5">
                                    <input class="form-check-input" type="radio" name="semester" value="summer" />
                                    <label class="form-check-label">Summer</label>
                                </div>
                                <div class="form-check form-check-inline me-5">
                                    <input class="form-check-input" type="radio" name="semester" value="fall" />
                                    <label class="form-check-label">Fall</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3 col-6">
                        <label class="form-label"><b>Select Department</b></label>
                        <select class="form-select" name="dpt_name" required>
                            <option selected value="0" disabled>Select Department</option>
                            <option value="cse">Department of Computer Science & Engineering</option>
                            <option value="eee">Department of Electrical and Electronic Engineering</option>
                            <option value="b_pharm">Department of Pharmacy</option>
                            <option value="ce">Department of CivilEngineering</option>
                        </select>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" value="checkbox" name="checkbox" required />
                        <label class="form-check-label">
                            I to Agree the Terms and Conditions
                        </label>
                    </div>
                    <button type="submit" class="btn btn-dark btn-sm form-control">Submit</button>
                </div>
            </div>
        </div>
    </form>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</html>